name: Build deploy kubernetes
on:
    push:
      branches:
        - main
    workflow_dispatch:
jobs:
    build-and-deploy:
        runs-on: 
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Log into Docker Hub
            uses: docker/login-action@v2
            with:
                username: ${{secrets.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_TOKEN}}

          - name: Build image
            run: |
                cd jokeDatabase
                docker build -t rachelallen1/joke-client-web-student:${{github.run_number}} .

          - name: Push image
            run: |
                docker push rachelallen1/joke-client-web-student:${{github.run_number}}

          - name: Deploy to kubernetes
            run: |
                export PATH=$PATH:~/.nix-profile/bin:/nix/var/nix/profiles/default/bin

                export IMAGE_TAG=${{github.run_number}}
                for file in kube/*; do
                    cat "$file" | envsubst | kubectl apply -f -;
                done

        #   - name: config map for postgres database
        #     run: |
        #         kubectl -n rjoke delete configmap rachel-recipe-postgres || true
        #         kubectl -n rachel create configmap rachel-recipe-postgres --from-file=init.sql
        #         echo "we did indeed run the config map part"